---
driver:
  name: docker
  privileged: true
  run_command: /bin/systemd
  cap_add:
    - SYS_ADMIN

provisioner:
  name: ansible_playbook
  hosts: test
  playbook: playbook.yml
  ansible_inventory: kitchen-hosts
  ansible_verbose: true

platforms:
  - name: debian-12

suites:
  - name: default
