---
driver:
  name: docker
  privileged: true
  run_command: /bin/systemd
  require_chef_omnibus: false
  cap_add:
    - SYS_ADMIN

provisioner:
  name: ansible_playbook
  hosts: test
  playbook: playbook-zds.yml
  ansible_inventory: kitchen-zds-hosts
  ansible_verbose: true
  requirements_collection_path: requirements.yml
  additional_copy_path: requirements.yml

platforms:
  - name: debian-12

suites:
  - name: default
