---
- name: deploy zds-site
  hosts: zds
  become: true
  roles:
    - role: common
      tags: bootstrap
    - role: backup
      tags: bootstrap
    - role: typesense
      tags: bootstrap
    - role: mysql
      tags: bootstrap
    - role: web
      tags: bootstrap
    - role: firewall
      tags: bootstrap
    - app
    - latex
    - role: zdsantispam
      tags: bootstrap
      when: env == "beta"
    - role: munin
      tags: bootstrap
    # - role: vaultwarden  # not used in practice
      # tags: bootstrap
      # when: (env == "prod") or (env == "vagrant")
