- name: create backup folder on beta server
  ansible.builtin.file:
    path: "{{ backupdir }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - zds-prod
    - zds-matomo

- name: create backup users on beta server
  ansible.builtin.user:
    name: "{{ item }}"
    home: "/home/{{ item }}"
    password: '!' # will do --disabled-password of adduser
  with_items:
    - zds-prod
    - zds-matomo

- name: create .ssh folders for backup users on beta server
  ansible.builtin.file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: u=rwx,g=,o=
  with_items:
    - zds-prod
    - zds-matomo

- name: create .ssh/authorized_keys files for backup users on beta server
  ansible.builtin.file:
    path: "/home/{{ item }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: u=rw,g=,o=
  with_items:
    - zds-prod
    - zds-matomo

- name: create folder for borg data and database
  ansible.builtin.file:
    path: "{{ backupdir }}/{{ item }}"
    state: directory
    owner: zds-prod
    group: zds-prod
    mode: u=rwx,g=,o=
  with_items:
    - db
    - data

- name: create folder for borg matomo
  ansible.builtin.file:
    path: "{{ backupdir }}/matomo"
    state: directory
    owner: zds-matomo
    group: zds-matomo
    mode: u=rwx,g=,o=

- name: create backup cleaning script on beta server
  ansible.builtin.template:
    src: beta/cleaning.sh.j2
    dest: /root/bin/backup_cleaning.sh
    mode: u=rwx,g=r,o=

- name: create script to restore backup on beta server
  ansible.builtin.template:
    src: beta/restore-from-prod.sh.j2
    dest: /root/bin/restore-from-prod.sh
    mode: u=rwx,g=r,o=
