- name: Install firewall (ufw)
  ansible.builtin.apt:
    pkg: ufw
    cache_valid_time: 3600

- name: Configure firewall (ufw) rules
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  loop:
    - "80"  # HTTP
    - "443"  # HTTPS
    - "22"  # SSH
    - "4949"  # Munin
    - "25"  # SMTP
    - "465"  # SMTP
    - "587"  # SMTP

- name: Enable firewall (ufw)
  community.general.ufw:
    state: enabled

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Log firewall only in /var/log/ufw.log
  # otherwise /var/log/{kern.log,messages,syslog} get full of [UFW BLOCK] messages
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.d/20-ufw.conf
    search_string: "#& stop"
    line: "& stop"
  notify: reload rsyslog
