- name: Create Geodata folder
  ansible.builtin.file:
    path: "{{ appdir }}/geodata"
    state: directory
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - bootstrap

- name: Install GeoLite updater script
  ansible.builtin.template:
    src: templates/update-geolite.sh.j2
    dest: "{{ workdir }}/update-geolite.sh"
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
    mode: u=rwx,g=r,o=
  tags:
    - bootstrap

- name: Initial download of GeoLite data  # noqa command-instead-of-shell no-changed-when
  ansible.builtin.shell: "{{ workdir }}/update-geolite.sh"
  tags:
    - bootstrap

- name: Setup cron to daily update GeoLite data
  ansible.builtin.cron:
    name: "Update GeoLite data"
    special_time: daily
    job: "{{ workdir }}/update-geolite.sh"
  tags:
    - bootstrap
