---
- name: run texhash # noqa no-changed-when
  become: true
  become_user: "{{ appuser }}"
  ansible.builtin.command: texhash {{ workdir }}/texmf

- name: refresh font-config cache # noqa no-changed-when
  ansible.builtin.command: fc-cache -f
