- name: add elasticsearch repository key
  ansible.builtin.apt_key:
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    keyserver: "hkp://keyserver.ubuntu.com:80"

- name: add elasticsearch repository
  ansible.builtin.apt_repository:
    filename: elasticsearch
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    state: present

- name: install openjdk-17-jre-headless and elasticsearch
  ansible.builtin.apt:
    pkg:
      - openjdk-17-jre-headless
      - elasticsearch
    cache_valid_time: 3600

- name: copy elasticsearch config files
  ansible.builtin.copy:
    src: jvm.options
    dest: /etc/elasticsearch/jvm.options
    mode: u=rw,g=rw
  notify: restart elasticsearch

- name: start elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch.service
    state: started
    enabled: true
