name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          pip-install: -r requirements.txt
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: Execute pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  test:
    name: Execute playbooks
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        playbook: [zds, matomo]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Ruby and Ruby gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          pip-install: -r requirements.txt
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: disable apparmor profile for mysqld # Needed to start mariadb server without AppArmor getting in the way
        run: >
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/;
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld;
          sudo aa-status

      - name: Run Kitchen tests for ${{ matrix.playbook }}
        run: bundle exec kitchen test
        env:
          KITCHEN_YAML: kitchen-${{ matrix.playbook }}.yml
